name: CrazyCrates
main: me.badbones69.crazycrates.Main
author: BadBones69
version: 1.7.2.0
softdepend: [MVdWPlaceholderAPI, PlaceholderAPI]
description: Want some good quality crates without paying money for them? Then check this crate plugin out.
commands:
  CrazyCrates:
    description: Opens the GUI.
    aliases: [cc, ccrate, crazycrate, crate, crates]
